@echo off
echo Starting CryptoMiner Admin Dashboard...
echo.
echo Starting Backend Server...
start cmd /k "cd backend && npm run dev"
timeout /t 3 /nobreak > nul
echo.
echo Starting Admin Panel...
start cmd /k "cd adminpanel && npm run dev"
echo.
echo Both servers are starting...
echo Backend: http://localhost:3000
echo Admin Panel: http://localhost:5173
